### ISSUE TITLE
div issues

### ISSUE THREAD

**Issue by lu171** [exc-asia-and-europe/ecpo#21]
I have been adding writing mode and direction to issue 1939-04-24 page 2 and 3. 

I was following the example of the header in the wiki page 04 XML Structure, and div without attributes like type are deemed errors in my interface,
 e.g. 
the div before 晶報 
the div dir="ltr" mode="horizontal-tb" before  The Crystal.

**Comment by duncdrum** [comment]
This is likely an error with the schema resolution. Divs without `@type` are allowed. can you show me the exact error?
