### ISSUE TITLE
whitespaces ideographic?

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo#3]
should we use `U+3000` during transcription or should we use default whitespace. When should whitespaces be transcribed and when can they be ignored

**Comment by Kuo-Teng-Feng** [comment]
We already used U+3000 on "〇" (zero、零)。

**Comment by duncdrum** [comment]
yes`U+3007` = Ideographic Zero makes sense, 
i m inclined to go with Ideographic space as well when it is used inline to separate phrases. 
What about indentation?
