### ISSUE TITLE
Is the server down?

### ISSUE THREAD

**Issue by lu171** [exc-asia-and-europe/ecpo#38]
For the past several days, I had trouble accessing https://kjc-sv034.kjc.uni-heidelberg.de/ecpo and https://ecpo.existsolutions.com/exist/apps/ecpo/.

For the former, I could not enlarge any page: error loading image. 

For the latter, when I click any fold, it is just blank, nothing loaded. 

Any of you have run into the same problem?

**Comment by duncdrum** [comment]
I just checked both servers and they are up, try reloading your browser? I m not aware of recent outages, but its possible that they were down.

**Comment by duncdrum** [comment]
and now its down for me too,

**Comment by Kuo-Teng-Feng** [comment]
down, 3.

**Comment by duncdrum** [comment]
the orignal sever was damaged during a move operation, we're in the process of connecting the various bits to the new server, i ll let you know how things pan out.

**Comment by line-o** [comment]
The images are now loaded from the new IIIF-server, provided by the university IT.

- The base-URL for images in the image list was changed
- All annotations were migrated to point to the new sourcefile URLs
