### ISSUE TITLE
Reminder: the price of 晶報 was raised between 22.4~26.4.

### ISSUE THREAD

**Issue by Kuo-Teng-Feng** [exc-asia-and-europe/ecpo#54]
This seems to be ignored on the website information. Just a small reminder.

**Comment by MatthiasArnold** [comment]
thanks for reminding me. i've added the information to the publication history data

Issue no. 3795 (1938-04-21): 今日贰張售國幣贰分四厘
Issue no. 3796 (1938-04-22): 今日兩全張售國幣贰分四厘
