### ISSUE TITLE
Missing lines, misannotations and deciphered gaiji

### ISSUE THREAD

**Issue by konstantinhenke** [exc-asia-and-europe/ecpo#57]
When linking the ground truth files in all of the issues below, I was somewhat inconsistent between with those that have a "_re" version. So please check if the error should be corrected in the "_re" version instead of the original one that I might have linked instead. 

The following lines are missing:

The line above [this one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3804_1939-04-30_0001%2B0004.xml#L705).
The line above [this one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3795_1939-04-21_0001%2B0004.xml#L831).
The line above [this one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3796_1939-04-22_0006+0007.xml#L593). Since I needed it for the OCR ground truth, I annotated it as:
"到高價。他的演說集，在意國出售，誰不買它一冊，這筆錢就可觀咧。希特拉的".
The line above [this one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L76). Annotated it as:
"、與日軍巷戰二小時、短兵相&gaiji;、日軍棄城向東北潰走、華軍乃派隊收復高安、"

Other errors I found (below, "A → B" means "wrong annotation A should be corrected to actual print B"):

[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3795_1939-04-21_0002%2B0003.xml#L1080) is an additional 人 (美人之... → 美之...).
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3795_1939-04-21_0005+0008.xml#L244) and 2 and 4 lines later: 墨索里尼 → 莫索里尼. In the same paragraph, 2x 倫 → 侖. Searching for "墨索里尼" in the whole ground truth yields 18 results which should probably be checked for this as well.
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3795_1939-04-21_0002+0003.xml#L1075): 2x 梅 → 眉. There seem to be more instances of 眉峯 erroneously annotated as 梅峯.
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3799_1939-04-25_0005+0008.xml#L551): 的事 → 事的
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3795_1939-04-21_0005+0008.xml#L271): 的的 → 的
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3796_1939-04-22_0002+0003.xml#L193): 日漸增加 → 日見增加 (misprints shouldn't be corrected by the annotators).
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L107): "、" missing after 中午. Also [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L124) after 結果 and [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L462) before 歸該 and [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L552) and [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L613) at the beginning and [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L610) at the end of the line.
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L234): 人才 → 人材
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L310): 國家 → 國
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L420): The first 當 should be deleted.
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L423): Missing 之 after 按溫州甌江 and [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L418) after 溫州
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L453): Missing 省 after 浙江.
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L592): 建設建設 → 建設.
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0002+0003.xml#L747): Closing mark "」" missing after question mark.

There are multiple errors in [this](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L710) and the next line. They should be:
                    向工部局發言人、詢問該事<lb/>  
                    、據答、彼不能作任何批評<lb/>

[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L720): 國家 → 國民, also missing the closing "』" at the end of the paragraph. Also delete 日 [here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L805). (Who annotated this fold? There are so many errors!)

[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0002+0003.xml#L61): 正 → 現正
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0002+0003.xml#L30): 至 → 致
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0005+0008.xml#L31): 拍馬] → 拍馬 and in the line below: 憲法 → 憲
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0005+0008.xml#L606): 不太 → 大不
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0002+0003.xml#L751): 再二三 → 再而三
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0002+0003.xml#L638): 僅 → 謹
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3799_1939-04-25_0005+0008.xml#L37): 生子 → 生
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3799_1939-04-25_0005+0008.xml#L55): 沒有 → 沒

[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3796_1939-04-22_0002+0003.xml#L193) and many other cases: 款 → 欵, but I guess that's just an 異體字. Other 異體字 not differentiated between or inconsistently annotated are 為 → 爲, 卻 → 却, 眾 → 衆 and 回 → 囘.

Also, I deciphered some gaiji:

[This whole line](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3799_1939-04-25_0002%2B0003.xml#L906) should be changed to 利源鑿井工廠主 (the character 井 was missing as well).
In [this line](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3799_1939-04-25_0002%2B0003.xml#L994), the first gaiji is 麕, a variant of 麇 (the whole word is 麇集).
The gaiji in [this line](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0006+0007.xml#L69) is 髫 (the whole is 髫齡).
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3796_1939-04-22_0006+0007_re.xml#L828) is 𩓐 (apparently a variant of 脖).
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0001%2B0004.xml#L376) is 或.
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0001+0004.xml#L514) is 座.
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0001+0004.xml#L785) is 拏, a variant of 拿.
[These ones](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0002+0003.xml#L546) are 挈 (挈妻 makes sense) and most likely 爨 (whole word 炊爨).
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0002+0003.xml#L548) is most likely 慮.
[This part](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0002+0003.xml#L549) is 紅牆向黑門，門有銅環如浮漚者, can't read the last gaiji but 桐 → 銅!
[These three](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3797_1939-04-23_0002+0003.xml#L558) are 橘 and 饅首.
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L229) is 的 like the annotator suggested.
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L247) is 邇.
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L340) is 通 (whole word 交通).
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L466) is 潛.
[This one](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3798_1939-04-24_0001+0004.xml#L712) is 攷, a variant of 考 (whole word 攷慮).
[This source](http://www.ccfd.org.tw/ccef001/index.php?option=com_content&view=article&id=3218:2014-12-03-01-20-25&catid=438&Itemid=257&limitstart=1) can be used to correct all the gaiji in [this paragraph](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3796_1939-04-22_0006+0007.xml#L923) (鱔嶴幡; 祁; 錫; 表; 穡; 鹽鹺).

To keep things clean, I'll keep editing this comment as I find more errors. Once somebody starts correcting these please leave a comment so we don't get confused with what's a newly found error and what's already corrected.

**Comment by MatthiasArnold** [comment]
excellent post, thanks for pointing out all these issues, @konstantinhenke ! since we've started editing the GT now, i'd suggest that you open a new issue for new mistakes you find.

@ysmlouis Did you correct ALL of the problems? my suggestion is to mark those lines you corrected in the PR in *strikethrough*.

**Comment by ysmlouis** [comment]
Dear Matthias,

I have corrected all the issues (odd dates) found by Konstantin. Do you want me to record down those lines I have corrected? Sure, I can do it. So, please keep the message about the issues found by Konstantin first. I will make a list later. Thank you very much!

Best,
Suk Man

________________________________

**Comment by MatthiasArnold** [comment]
@ysmlouis - there is no need to document each individual correction. 
what we will need is a list of characteristic and systematic mistakes made by the editors, so we can use that document for training new editors later. you should collect these typical and repeating or systematic errors you can gather, together with @xiejia1995 . my suggestion is to do this on a new wiki page in this repo.
if all errors found by konstantin have been corrected in the ground truth you may close this ticket.
