### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by konstantinhenke** [exc-asia-and-europe/ecpo#78]
After [this line](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3800_1939-04-26_0002%2B0003.xml#L940), the following line is missing:
```
論知兩造以本案經<lb/>
```
[This line](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3800_1939-04-26_0002%2B0003.xml#L970) has two errors: 亦 is missing and there is only one character after 明珠大, probably 慚?
[Here](https://github.com/exc-asia-and-europe/ecpo/blob/master/jingbao/1939/04/jb_3801_1939-04-27_0002%2B0003.xml#L26) the character 歲 is missing

**Comment by xiejia1995** [comment]
yes, the first character should be  “諭”
`諭知兩造以本案經<lb/>`

i have corrected the first and second error in my branch, i will try to make a pull request.

**Comment by konstantinhenke** [comment]
Oh, I didn't look close enough, thanks for double-checking!

**Comment by xiejia1995** [comment]
@konstantinhenke we have found some 異體字 that we did not notice in 1939-04 issues. is it still possible that we make corrections in the files now? later I will post here what we found.

**Comment by konstantinhenke** [comment]
Yes, feel free to edit the files as needed and post the added pairs again here.

**Comment by xiejia1995** [comment]
update:

incorrect character + code point
correct character + code point

説 U+8AAC
說 U+8AAA

内 U+5185   
內 U+5167

**Comment by xiejia1995** [comment]
incorrect character + code point | correct character + code point
麽 U+9EBD  |  麼 U+9EBC 
羡 U+7FA1  |  羨 U+7FA8
聼 U+807C  |  聽 U+807D

**Comment by xiejia1995** [comment]
this pair of characters has not been replaced, but will do.
尚 U+5C1A --> 尙 U+5C19

**Comment by MatthiasArnold** [comment]
@xiejia1995 please close this issue once all mistakes were added to the GT and the character pairs are documented in the separate list.
